CircularLogic/CircularLogic.UI/Controllers/BlogPostController.cs
using CircularLogic.Data;
using CircularLogic.Models;
using CircularLogic.UI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CircularLogic.UI.Controllers
{
    public class BlogPostController : Controller
    {
        private BlogRepository _repo = new BlogRepository();

        //GET: BlogPost
        public ActionResult Index()
        {
            return View();
        }

        // GET: BlogPost / Create
        [Authorize]
        public ActionResult CreateBlogPost()
        {
            string name = User.Identity.Name;
            var firstOrDefault = new ApplicationDbContext().Users.FirstOrDefault(u => u.UserName == name);

            string id = firstOrDefault.Id;
            var CreateBlogPostVM = new BlogPostViewModel(new BlogPost() { UserID = id }, _repo.GetAllCategories());
            return View("CreateBlogPost", CreateBlogPostVM);
        }

        // Post / BlogPost
        [HttpPost]
        public ActionResult CreateBlogPost(BlogPost blogPost)
        {
            blogPost.CreationTime = DateTime.Now;
            blogPost.UpdateTime = DateTime.Now;
            if (User.IsInRole("Admin"))
            {
                blogPost.IsApproved = true;
            }
            else
            {
                blogPost.IsApproved = false;
            }
            List<string> tags;
            if (Request.Form["hiddenTagListA"].Contains(','))
            {
                tags = Request.Form["hiddenTagListA"].Split(',').ToList();
            }
            else
            {
                tags = new List<string>();
                tags.Add(Request.Form["hiddenTagListA"]);
            }
            
            List<Tag> existingTags = _repo.GetAllTags();
            foreach (string s in tags)
            {
                Tag tag = existingTags.FirstOrDefault(t => t.Name.ToUpper() == s.ToUpper());
                if (tag != null)
                {
                    blogPost.Tags.Add(tag);
                }
                else
                {
                    blogPost.Tags.Add(new Tag() { Name = s, TagID = 0 });
                }
            }
            _repo.CreateBlogPost(blogPost);
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Admin");
            }
            return RedirectToAction("ContributorHistory","Admin");
        }

        public ActionResult BlogPostDetail(int id)
        {
            BlogPost blogPost = _repo.GetBlogPostByBlogID(id);
            BlogPostViewModel blogPostVM = new BlogPostViewModel(blogPost);
            ViewBag.Title = blogPostVM.BlogPost.Title;
            return View(blogPostVM);
        }

        public ActionResult BlogHomePage(int? tagId)
        {
            IOrderedEnumerable<BlogPost> allPosts = _repo.GetAllBlogPosts().Where(p => p.IsApproved).OrderByDescending(p => p.CreationTime);
            if (tagId.HasValue)
            {
                allPosts = allPosts.Where(p => p.Tags.Any(t => t.TagID == tagId.Value)).OrderByDescending(p => p.CreationTime);
            }
            var listOfBlogViewModels = new List<BlogPostViewModel>();
            foreach (var blogPost in allPosts)
            {
                BlogPostViewModel bpVM = new BlogPostViewModel(blogPost);
                listOfBlogViewModels.Add(bpVM);
            }
            return View("BlogHomePage", listOfBlogViewModels);
        }

        public ActionResult AddCategory()
        {
            return PartialView("AddCategory");
        }

        public ActionResult EditBlog(int id)
        {
            BlogPostViewModel bpvm = new BlogPostViewModel(_repo.GetBlogPostByBlogID(id), _repo.GetAllCategories());
            return View(bpvm);
        }

        [HttpPost]
        public ActionResult EditBlog(BlogPost blogPost)
        {
            blogPost.CreationTime = DateTime.Now;
            blogPost.UpdateTime = DateTime.Now;
            if (User.IsInRole("Admin"))
            {
                blogPost.IsApproved = true;
            }
            else
            {
                blogPost.IsApproved = false;
            }
            List<string> tags;
            if (Request.Form["hiddenTagListA"].Contains(','))
            {
                tags = Request.Form["hiddenTagListA"].Split(',').ToList();
            }
            else
            {
                tags = new List<string>();
                tags.Add(Request.Form["hiddenTagListA"]);
            }

            List<Tag> existingTags = _repo.GetAllTags();
            foreach (string s in tags)
            {
                Tag tag = existingTags.FirstOrDefault(t => t.Name.ToUpper() == s.ToUpper());
                if (tag != null)
                {
                    blogPost.Tags.Add(tag);
                }
                else
                {
                    blogPost.Tags.Add(new Tag() { Name = s, TagID = 0 });
                }
            }
            _repo.EditABlogPost(blogPost);
            return RedirectToAction("ContributorHistory", "Admin");
        }

        public ActionResult Blogs()
        {
            return View();
        }

        public JsonResult GetTagCloudTags()
        {
            return Json(_repo.GetAllSumOfTags().Select(model => new
            {
                text = model.Name,
                weight = model.Weight,
                html = new { myId = model.TagCloudID, Class = "tagLink" }
            }), JsonRequestBehavior.AllowGet);
        }
    }
}

CircularLogic/CircularLogic.UI/Controllers/StaticPageController.cs
using CircularLogic.Data;
using CircularLogic.Models;
using CircularLogic.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CircularLogic.UI.Controllers
{
    public class StaticPageController : Controller
    {
        private StaticPageRepository _repo = new StaticPageRepository();

        // GET: StaticPage
        [Authorize]
        public ActionResult AddStaticPage()
        {
            var addStaticPage = new StaticPage();
            return View("AddStaticPage", addStaticPage);
        }

        [HttpPost]
        public ActionResult AddStaticPage(StaticPage staticPage)
        {
            staticPage.CreationTime = DateTime.Now;
            staticPage.UpdateTime = DateTime.Now;

            int id = _repo.AddAStaticPage(staticPage);

            return RedirectToAction("ViewStaticPage", new { id = id });
        }

        public ActionResult ViewStaticPage(int id)
        {
            var viewStaticPage = _repo.GetStaticPageByStaticPageID(id);
            ViewBag.Title = viewStaticPage.Title;
            return View(viewStaticPage);
        }

        public ActionResult UpdateStaticPage(int id)
        {
            StaticPage spVM = new StaticPage();
            spVM = _repo.GetStaticPageByStaticPageID(id);
            return View(spVM);
        }

        [HttpPost]
        public ActionResult UpdateStaticPage(StaticPage staticPage)
        {
            staticPage.UpdateTime = DateTime.Now;

            _repo.UpdateAStaticPage(staticPage);
            return RedirectToAction("ViewStaticPage", staticPage.StaticID);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteStaticPage(StaticPage staticPage)
        {
            _repo.DeleteStaticPageByID(staticPage.StaticID);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteStaticPage(int id)
        {
            var staticPageID = _repo.GetStaticPageByStaticPageID(id);

            return View(staticPageID);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var models = _repo.GetAllStaticPages();

            return View(models);
        }

        public PartialViewResult MenuDropDown()
        {
            return PartialView("_StaticList", _repo.GetAllStaticPages());
        }
    }
}

CircularLogic/CircularLogic.UI/Views/Shared/AddCategory.cshtml
@model CircularLogic.Models.Category
@*
    -Name of category
        +check if it exists
    -Color of category
        +check if it exists
        + #e79c00 (logo Orange)

    - AJAX add the category if it is Gucci

    -SNARL the entry on the main page

    @{Html.RenderPartial("AddCategory");}
*@

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add a Category</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon3">Name:</span>
                        <input type="text" class="form-control" id="catName" aria-describedby="basic-addon3">
                    </div>
                </div>
                <br/>
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="jscolor {valueElement:'chosen-value', onFineChange:'setTextColor(this)', closable:true,closeText:'Close'} btn btn-primary" id="jscButton">
                                Pick a color
                            </button>
                        </span>
                        <input id="chosen-value" value="000000" class="form-control"/>
                    </div>
                </div>

                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="addCatBtn" data-dismiss="modal">Create</button>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript" src="~/Scripts/app/AddCategory.js" defer="defer"></script>
@Scripts.Render("~/Scripts/app/jscolor.min.js")

CircularLogic/CircularLogic.UI/Views/Shared/_BlogPagesView.cshtml
<!DOCTYPE html>
<html style="margin: 0; min-height: 100%; width: 100%;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dev's Round Table - @ViewBag.Title</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href="~/Content/tile.css" rel="stylesheet">
    <link href="~/Content/sidebars.css" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jquery.share.css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/jqcloud.min.css" rel="stylesheet" />
</head>
<body style="min-height: 100%;" id="myPage" data-spy="scroll" data-target=".navbar">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Circular Logic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="padding-top: 50px;">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Blog", "Blogs", "BlogPost")</li>
                    @if (User.IsInRole("Admin") || User.IsInRole("Contributor"))
                    {
                        <li class="dropdown">
                            @if (@User.IsInRole("Admin"))
                            {
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin <b class="caret"></b></a>
                            }
                            else
                            {
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Contributor <b class="caret"></b></a>
                            }
                            <ul class="dropdown-menu" id="menu1" style="border-top: 0!important">
                                <li>
                                    <a href="#">Blog <i class="glyphicon glyphicon-chevron-right pull-right"></i></a>
                                    <ul class="dropdown-menu sub-menu">
                                        <li>@Html.ActionLink("Create", "CreateBlogPost", "BlogPost")</li>
                                        @if (!User.IsInRole("Admin"))
                                        {
                                            <li>@Html.ActionLink("History", "ContributorHistory", "Admin")</li>
                                        }
                                    </ul>
                                </li>

                                @if (User.IsInRole("Admin"))
                                {
                                    <li>
                                        <a href="#">Static Page<i class="glyphicon glyphicon-chevron-right pull-right"></i></a>
                                        <ul class="dropdown-menu sub-menu">
                                            <li>@Html.ActionLink("Add", "AddStaticPage", "StaticPage")</li>
                                            <li>@Html.ActionLink("Manage", "Index", "StaticPage")</li>
                                        </ul>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#" id="loadCatModal">Add Category</a></li>
                                    <li>@Html.ActionLink("Admin Queue", "Index", "Admin")</li>
                                }
                            </ul>
                        </li>
                    }
                    @{Html.RenderAction("MenuDropDown", "StaticPage");}
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div id="wrapper" style="padding-top: 50px">
        <!-- Left Sidebar -->
        <div id="sidebar-wrapper-left">
            <div id="SocialShare" lass="share-affix" style="left: 0; right: auto; top: 65%">
            </div>
        </div>

        <!-- Right Sidebar -->
        <div id="sidebar-wrapper-right" class="hidden-phone hidden-xs">
            <div id="tagsContainer" style="width: 100%; height: 40%;">
                <div id="tags"> </div>
            </div>
            <div class="fb-page" data-href="https://www.facebook.com/circlog/" data-width="250" data-small-header="false"
                 data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" style="margin-left: 3%; margin-top: 2%;">
                <div class="fb-xfbml-parse-ignore">
                    <blockquote cite="https://www.facebook.com/circlog/"><a href="https://www.facebook.com/circlog/">Circular Logic</a></blockquote>
                </div>
            </div>
            <div style="margin-left: 3%; margin-top: 5%; margin-bottom: -15px;">
                <a href="https://twitter.com/circularlogic" class="twitter-follow-button" data-show-count="false" data-size="large">"Follow @("@")username"</a>
            </div>
            @*<div style="margin: 50px; width: 300px">
                    <h2 style="text-align: center;">About Our Blog</h2>
                    <p style="font-size: 10px;">
                        The Dev’s Round Table is a blog managed by our in house development team.
                        We utilize this blog to share our team’s view on core programming principles with the world.
                        Posts touch on a wide range of topics from low level topics such as assembly languages to high
                        level concepts like user experience. Our hope is that this blog can provide a window for our
                        clients to observe our development strategies and reference for other development teams to get
                        insight into our team’s thought process. The blog has also proven to be a useful training tool
                        for new team members of all skill levels, as it helps bring them up to speed with the types of
                        concepts they will see implemented on projects and insight into the core value of our development team.
                    </p>
                </div>*@
        </div>

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <div id="addCatModalHolder"></div>

        <hr />
        <footer class="container-fluid text-center">
            <a href="#myPage" title="To Top">
                <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
            <br />
            <img src="~/Content/Logos/CL_100x100.png" />
            <br />
            <p>Est. 2016, sponsored by Red Bull</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/app/snarl.min.js")
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Scripts/app/AngularLib/angular.js"></script>
    <script src="~/Scripts/app/AngularLib/angular-route.min.js"></script>
    <script src="~/Scripts/app/AngularLib/dirPagination.js"></script>
    <script src="~/Scripts/app/jquery.share.js"></script>
    <script src="~/Scripts/app/sidebars.js"></script>

    <script type="text/javascript">
        $("img").error(function () {
            $(this).hide();
        });
        $('#SocialShare')
            .share({
                networks: ['twitter', 'facebook', 'pinterest'],
                orientation: 'vertical',
                theme: 'square',
                urlToShare: '@Request.Url.AbsoluteUri',
                affix: 'left center'
            });
    </script>

    <script src="~/Scripts/app/jqcloud.js"></script>
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $.getJSON('@Url.Action("GetTagCloudTags", "BlogPost")', function (data) {
                $("#tags").jQCloud(data, { width: ('100%'), height: ('100%') });
                window.dispatchEvent(new Event('resize'));

            });
            $(document).on("click", ".tagLink", function (event) {
                var tag = $(this);
                var txt = tag[0].innerHTML;
                $('#blgSearch').val(txt);
                $('#blgSearch').trigger('input');
                var url = '@Url.Action("BlogHomePage","BlogPost")';
                //window.location.href = url + "?tagId=" + tag.attr("myId");
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            // Add smooth scrolling to all links in navbar + footer link
            $("footer a[href='#myPage']").on('click', function (event) {

                // Prevent default anchor click behavior
                event.preventDefault();

                // Store hash
                var hash = this.hash;

                // Using jQuery's animate() method to add smooth page scroll
                // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                $('html, body').animate({
                    scrollTop: $(hash).offset().top
                }, 900, function () {

                    // Add hash (#) to URL when done scrolling (default click behavior)
                    window.location.hash = hash;
                });
            });
        })
    </script>
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.6";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>
        $(document).ready(function (d, s, id) {
            var js,
                fjs = d.getElementsByTagName(s)[0],
                p = /^http:/.test(d.location) ? 'http' : 'https';
            if (!d.getElementById(id)) {
                js = d.createElement(s);
                js.id = id;
                js.src = p +
                    '://platform.twitter.com/widgets.js';
                fjs.parentNode.insertBefore(js, fjs);
            }
        }(document, 'script', 'twitter-wjs'));
    </script>
    <script type="text/javascript">
        $(document)
            .ready(function () {
                $("img")
                    .error(function () {
                        $(this).hide();
                    });
                jQuery.ajaxSetup({ async: false });
                $('#loadCatModal')
                    .click(function () {
                        $('#addCatModalHolder').load('/Admin/AddCategory');
                        $("#myModal").modal();
                    });
            });
    </script>
</body>
</html>

CircularLogic/CircularLogic.UI/Views/Shared/_BlogTilePartial.cshtml
@model CircularLogic.UI.Models.BlogPostViewModel

<a href="@Url.Action("BlogPostDetail", "BlogPost", new {id = Model.BlogPost.BlogPostID})" class="tile-link col-lg-3 col-md-4 col-sm-6 col-xs-12">
    <div class="blog-tile">
        <div class="tile-title" @if (@Model.BlogPost.Category.Color.Length > 1)
                                {
                                    @:style="background-color: #@Model.BlogPost.Category.Color" 
                                }>
            <div class="tile-date">@Model.BlogPost.CreationTime.ToString("MMM dd yyyy")</div>
        </div>
        <div class="tile-image-container">
            <div class="tile-image">
                <img src="@Model.BlogPost.Image.ImageData" style='height: 130px; width: 100%; object-fit: contain'>
            </div>
        </div>
        <div class="tile-title-text-container">
            <div class="tile-title-text ">@Model.BlogPost.Title</div>
        </div>
        <div class="tile-author-container">
            <div class="tile-author">@Model.User.FirstName @Model.User.LastName</div>
        </div>
        <div class="tile-tags-container">
            <div class="tile-tags">
                @foreach (var tag in Model.BlogPost.Tags)
                {
                    <span>@tag.Name.ToUpper() |</span>
                }
            </div>
        </div>
        <div class="tile-fadeout"> </div>
    </div>
</a>

@section scripts{
<script type="text/javascript">
    $(document)
        .ready(function() {
            $("img")
                .error(function() {
                    $(this).hide();
                });
        });
</script>
}

CircularLogic/CircularLogic.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Circular Logic - @ViewBag.Title</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href="~/Content/tile.css" rel="stylesheet">
    <link href="~/Content/sidebars.css" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Scripts/app/snarl.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="min-height: 100%;" id="myPage" data-spy="scroll" data-target=".navbar">

    <div class="navbar navbar-inverse navbar-fixed-top">
        @*<div class="masthead-container">
                <div class="masthead-image">
                    <img src="~/Content/Images/lowPolyOrange2.jpg" />
                </div>
            </div>
            <div class="masthead-fadeout"> </div>*@
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Circular Logic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="padding-top: 50px;">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Blog", "Blogs", "BlogPost")</li>
                    @if (User.IsInRole("Admin") || User.IsInRole("Contributor"))
                    {
                        <li class="dropdown">
                            @if (@User.IsInRole("Admin"))
                            {
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin <b class="caret"></b></a>
                            }
                            else
                            {
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Contributor <b class="caret"></b></a>
                            }
                            <ul class="dropdown-menu" id="menu1" style="border-top: 0!important">
                                <li>
                                    <a href="#">Blog <i class="glyphicon glyphicon-chevron-right pull-right"></i></a>
                                    <ul class="dropdown-menu sub-menu">
                                        <li>@Html.ActionLink("Create", "CreateBlogPost", "BlogPost")</li>
                                        @if (!User.IsInRole("Admin"))
                                        {
                                            <li>@Html.ActionLink("History", "ContributorHistory", "Admin")</li>
                                        }
                                    </ul>
                                </li>
                               
                                @if (User.IsInRole("Admin"))
                                {
                                    <li>
                                        <a href="#">Static Page<i class="glyphicon glyphicon-chevron-right pull-right"></i></a>
                                        <ul class="dropdown-menu sub-menu">
                                            <li>@Html.ActionLink("Add", "AddStaticPage", "StaticPage")</li>
                                            <li>@Html.ActionLink("Manage", "Index", "StaticPage")</li>
                                        </ul>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#" id="loadCatModal">Add Category</a></li>
                                    <li>@Html.ActionLink("Admin Queue", "Index", "Admin")</li>
                                }
                            </ul>
                        </li>
                    }
                    @{Html.RenderAction("MenuDropDown", "StaticPage");}
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="container body-content">

        @RenderBody()
        <div id="addCatModalHolder"></div>
        <hr />
        <footer class="container-fluid text-center">
            <a href="#myPage" title="To Top">
                <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
            <br />
            <img src="~/Content/Logos/CL_100x100.png" />
            <br />
            <p>Est. 2016, sponsored by Red Bull</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/app/snarl.min.js")
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Scripts/app/AngularLib/angular.js"></script>
    <script src="~/Scripts/app/AngularLib/angular-route.min.js"></script>
    <script src="~/Scripts/app/AngularLib/dirPagination.js"></script>
    <script src="~/Scripts/app/konami.js"></script>
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document)
            .ready(function () {
                var easter_egg = new Konami(function () {
                    $('body').empty();
                    $('body')
                        .css({
                            'height': $(window).height(),
                            'width': '100%',
                            'overflow': 'hidden',
                            'margin': '0px',
                            'background-color': 'rgb(38, 38, 38)'
                        });
                    $('body')
                        .append('<embed width="100%" height="100%" name="plugin" id="plugin" src="http://blackacrebrewing.com/hey.swf" type="application/x-shockwave-flash">');
                });
                $("img")
                    .error(function () {
                        $(this).hide();
                    });
                //jQuery.ajaxSetup({ async: false });
                $('#loadCatModal')
                    .click(function () {
                        $.get('/Admin/AddCategory', function (data) {
                            $('#addCatModalHolder').replaceWith(data);
                            $("#myModal").modal();
                        });
                        //$('#addCatModalHolder').load('/Admin/AddCategory', function() {
                        //    $("#myModal").modal();
                        //});
                        //jQuery.ajaxSetup({ async: true });
                    });

            });
    </script>
    <script>
        $(document).ready(function () {
            // Add smooth scrolling to all links in navbar + footer link
            $("footer a[href='#myPage']").on('click', function (event) {

                // Prevent default anchor click behavior
                event.preventDefault();

                // Store hash
                var hash = this.hash;

                // Using jQuery's animate() method to add smooth page scroll
                // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                $('html, body').animate({
                    scrollTop: $(hash).offset().top
                }, 900, function () {

                    // Add hash (#) to URL when done scrolling (default click behavior)
                    window.location.hash = hash;
                });
            });
        })
    </script>
</body>
</html>

CircularLogic/CircularLogic.UI/Views/Shared/_StaticList.cshtml
@model List<CircularLogic.Models.StaticPage>
<li class="dropdown">
    <a href="#" data-toggle="dropdown" class="dropdown-toggle">More Pages <b class="caret"></b></a>
    <ul class="dropdown-menu" id="menu2">
       @foreach (var m in Model)
       {
        <li>@Html.ActionLink(@m.LinkName, "ViewStaticPage", "StaticPage", new {id=@m.StaticID}, null)</li>
       }
    </ul>
</li>